[webservers]
ansible-slave1 ansible_host=172.30.244.182 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3

[jenkins_servers]
jenkins-master ansible_host=172.30.254.157 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3